### ISSUE TITLE
storageClassName missing in the CRD

### ISSUE THREAD

**Issue by Baykonur** [mongodb/mongodb-kubernetes-operator#61]
Hello,

How can we specify the `storageClassName` for the `sts` getting created by the operator? 

In the [example](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/deploy/crds/mongodb.com_v1_mongodb_cr.yaml) and in the [crd definition](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/deploy/crds/mongodb.com_mongodb_crd.yaml) I do not see any place where to set it up.

**Comment by chatton** [comment]
Hi @Baykonur,

Additional configuration of the StatefulSet created by the operator is not yet supported through the CRD.

This issue is being tracked internally by [CLOUDP-65312](https://jira.mongodb.org/browse/CLOUDP-65312)

**Comment by Baykonur** [comment]
Thanks, any indication when we can get this feature available?

**Comment by chatton** [comment]
Hi @Baykonur, this is going to be one of the next features we work on, so it should be coming soon, likely next week or 2.

**Comment by kaykhancheckpoint** [comment]
Any update on this, its also a feature i require

**Comment by fabianlindfors** [comment]
Sorry about the auto-closing. This issue should be fixed with #118 which will be included in the next release. The PR adds the ability to add arbitrary configuration of the StatefulSet, including the `storageClassName`.

**Comment by chatton** [comment]
Hi @Baykonur, @kaykhancheckpoint 

It is now possible to modify the StorageClass name and other stateful set values via the CRD. See the PR https://github.com/mongodb/mongodb-kubernetes-operator/pull/157 as an example.

**Comment by samaiyayashraj** [comment]
Hello @chatton , Sorry to reopen this issue but I still can't find the storageclass name in the CRD. PFA yaml I'm using create a MongoDB instance using MongoDB community operator.
Here basically I want to use my custom storageclass to create PVC but somehow it's not taking the SC name & it's going in pending state. 
[example.txt](https://github.com/mongodb/mongodb-kubernetes-operator/files/6432508/example.txt)

**Comment by chatton** [comment]
Hi @samaiyayashraj

Are you trying to update the `storageClassName` of an existing StatefulSet? This property cannot be changed and you should get an error that looks like 

```
StatefulSet.apps "quick-start-rs" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

However if you are creating a fresh resource and it is still not working, I am unable to produce that locally, I was however successfully able to **create** a resource with the overridden storage class name.

If you are still having this issue could you please provide the operator logs and the current state of your StatefulSet (`kubectl get sts <mdb-name> -o yaml`)

**Comment by samaiyayashraj** [comment]
Hi @chatton Thanks for the reply. 
So if you specify a storageclass which is not the default storageclass of your cluster then you can probably reproduce the issue. 
Here in the attachment, you can find the yaml file I'm using to create the mongoDB instance. 
Here I'm using
storageClassName: "vsan-default-storage-policy" & this is not the default SC of my cluster but when I make this as default SC then it works fine.

So according to me the MongoDB community operator only takes default SC somehow.
[example.txt](https://github.com/mongodb/mongodb-kubernetes-operator/files/6443629/example.txt)

**Comment by Daxcor69** [comment]
> However if you are creating a fresh resource and it is still not working, I am unable to produce that locally, I was however successfully able to **create** a resource with the overridden storage class name.

When creating a new resource, how do I specify the storageclass override. I have been looking everywhere and can't find the reference.

Thanks

**Comment by kaykhancheckpoint** [comment]
> > However if you are creating a fresh resource and it is still not working, I am unable to produce that locally, I was however successfully able to **create** a resource with the overridden storage class name.
> 
> When creating a new resource, how do I specify the storageclass override. I have been looking everywhere and can't find the reference.
> 
> Thanks

`persistence.storageClass`

**Comment by djniu** [comment]
I append the storageClassName in MongoDBCommunity yaml, and it is like below, but it is not working. By the way the size does work well.
`  
statefulSet:
    spec:
      template:
        spec:
          volumeClaimTemplates:
            - metadata:
                name: data-volume
              spec:
                resources:
                  requests:
                    storage: 10Gi
            - metadata:
                name: logs-volume
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: "azure-disk-hdd"
                resources:
                  requests:
                    storage: 2Gi`
