### ISSUE TITLE
Resource is invalid "status.version" errors

### ISSUE THREAD

**Issue by tliron** [mongodb/mongodb-kubernetes-operator#676]
**What did you expect?**
The operator is unable to update the CR's status and the logs are showing errors like this:
```
2021-08-06T16:29:06.553Z	ERROR	controllers/replica_set_controller.go:230	Error updating the status of the MongoDB resource: MongoDBCommunity.mongodbcommunity.mongodb.com "open5gs-mongodb" is invalid: status.version: Required value	{"ReplicaSet": "workspace/open5gs-mongodb"}
github.com/mongodb/mongodb-kubernetes-operator/controllers.ReplicaSetReconciler.Reconcile
	/workspace/controllers/replica_set_controller.go:230
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:298
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214
```
**More context**
Operator version 0.7.0.

Trying with various versions of MongoDB: 5.0.2, 4.4.8, 4.2.6

**Comment by tliron** [comment]
Workaround for now is to comment out [this line](https://github.com/mongodb/mongodb-kubernetes-operator/blob/ed9ec900804bef5f1fb278a39b29038d0feac604/config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml#L332).

**Comment by FlorentinaSimlinger** [comment]
Hi @tliron, unfortunately we weren't able to reproduce this error. Would you be able to share the custom resource yaml you are applying? Thanks

**Comment by tliron** [comment]
Sure:
```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity

metadata:
  name: open5gs-mongodb
  labels:
    app.kubernetes.io/name: open5gs-mongodb
    app.kubernetes.io/instance: open5gs-mongodb
    app.kubernetes.io/component: 5g
    app.kubernetes.io/part-of: open5gs
    app.kubernetes.io/managed-by: open5gs

spec:
  type: ReplicaSet
  members: 3
  version: 5.0.2
  security:
    authentication:
      modes: [ SCRAM ]
  users:
  - name: user
    db: admin
    passwordSecretRef:
      name: open5gs-mongodb-user-password
    roles:
    - name: root
      db: admin
    scramCredentialsSecretName: scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
    storage.wiredTiger.engineConfig.cacheSizeGB: 0.25
  # The defaults are 10GB persistent volume claims, we will reduce them here
  statefulSet:
    spec:
      volumeClaimTemplates:
      - metadata:
          name: data-volume
          labels:
            app.kubernetes.io/name: open5gs-mongodb
            app.kubernetes.io/instance: open5gs-mongodb-data
            app.kubernetes.io/version: $VERSION
            app.kubernetes.io/component: 5g
            app.kubernetes.io/part-of: open5gs
            app.kubernetes.io/managed-by: open5gs
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
      - metadata:
          name: logs-volume
          labels:
            app.kubernetes.io/name: open5gs-mongodb
            app.kubernetes.io/instance: open5gs-mongodb-logs
            app.kubernetes.io/version: $VERSION
            app.kubernetes.io/component: 5g
            app.kubernetes.io/part-of: open5gs
            app.kubernetes.io/managed-by: open5gs
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi

---

apiVersion: v1
kind: Secret

metadata:
  name: open5gs-mongodb-user-password

type: Opaque
stringData:
  password: password
```

**Comment by FlorentinaSimlinger** [comment]
Could you check please if the mdbc reaches running phase (kubectl describe mdbc open5gs-mongodb --> Status.Phase)?

**Comment by tliron** [comment]
Well, as you can see from the error, it fails exactly when it tries to update the Status, so there is no Status.Phase or anything else in Status. It seems that somehow the code is sending in an empty version string and thus fails the CRD's OpenAPIv3 schema.

By the way, the replica set *is* up and *does* work. This is only an issue with the operator failing to update the status.

**Comment by FlorentinaSimlinger** [comment]
>Workaround for now is to comment out this line.

Just to confirm, does the mdbc CR report running state in the status after making this change?
Would it be also possible for you to share more detailed operator logs, including the other error messages (if any)?

**Comment by tliron** [comment]
It does report running state. There is no "status" section in the CR (that is the error).

This is the only error I am seeing, in the operator logs. I imagine the issue happens somewhere in the code where the version is retrieved but I can't see anything in the logs about it. Here's the entire context:
```
2021-08-09T15:49:15.275Z	INFO	controllers/replica_set_controller.go:132	Reconciling MongoDB	{"ReplicaSet": "workspace/open5gs-mongodb"}
2021-08-09T15:49:15.275Z	DEBUG	controllers/replica_set_controller.go:134	Validating MongoDB.Spec	{"ReplicaSet": "workspace/open5gs-mongodb"}
2021-08-09T15:49:15.275Z	DEBUG	controllers/replica_set_controller.go:143	Ensuring the service exists	{"ReplicaSet": "workspace/open5gs-mongodb"}
2021-08-09T15:49:15.285Z	INFO	controllers/replica_set_controller.go:389	The service already exists... moving forward: services "open5gs-mongodb-svc" already exists	{"ReplicaSet": "workspace/open5gs-mongodb"}
2021-08-09T15:49:15.285Z	INFO	controllers/replica_set_controller.go:307	Creating/Updating AutomationConfig	{"ReplicaSet": "workspace/open5gs-mongodb"}
2021-08-09T15:49:15.298Z	DEBUG	scram/scram.go:165	Credentials have not changed, using credentials stored in: secret/scram-scram-credentials
2021-08-09T15:49:15.298Z	DEBUG	controllers/replica_set_controller.go:428	AutomationConfigMembersThisReconciliation	{"mdb.AutomationConfigMembersThisReconciliation()": 3}
2021-08-09T15:49:15.298Z	DEBUG	controllers/replica_set_controller.go:330	Waiting for agents to reach version 1	{"ReplicaSet": "workspace/open5gs-mongodb"}
2021-08-09T15:49:15.298Z	INFO	agent/agent_readiness.go:52	All 3 Agents have reached Goal state	{"ReplicaSet": "workspace/open5gs-mongodb"}
2021-08-09T15:49:15.298Z	INFO	controllers/replica_set_controller.go:287	Creating/Updating StatefulSet	{"ReplicaSet": "workspace/open5gs-mongodb"}
2021-08-09T15:49:15.305Z	DEBUG	controllers/replica_set_controller.go:297	Ensuring StatefulSet is ready, with type: RollingUpdate	{"ReplicaSet": "workspace/open5gs-mongodb"}
2021-08-09T15:49:15.305Z	DEBUG	controllers/replica_set_controller.go:202	Resetting StatefulSet UpdateStrategy to RollingUpdate	{"ReplicaSet": "workspace/open5gs-mongodb"}
2021-08-09T15:49:15.309Z	ERROR	controllers/replica_set_controller.go:230	Error updating the status of the MongoDB resource: MongoDBCommunity.mongodbcommunity.mongodb.com "open5gs-mongodb" is invalid: status.version: Required value	{"ReplicaSet": "workspace/open5gs-mongodb"}
github.com/mongodb/mongodb-kubernetes-operator/controllers.ReplicaSetReconciler.Reconcile
	/workspace/controllers/replica_set_controller.go:230
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:298
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214
```

**Comment by FlorentinaSimlinger** [comment]
Hi @tliron we indeed had an issue with backward compatibility. It is fixed now and the changes are in master. Here's the link to the PR https://github.com/mongodb/mongodb-kubernetes-operator/pull/684

**Comment by tliron** [comment]
@FlorentinaSimlinger I see it required a code change, so does this mean I need to rebuild the operator to verify this fix?

**Comment by trilliot** [comment]
This issue is still causing troubles on commit 9ec2dcf:

```
2021-09-08T21:20:36.786Z	INFO	controllers/replica_set_controller.go:132	Reconciling MongoDB	{"ReplicaSet": "development/mongodb"}
2021-09-08T21:20:36.786Z	DEBUG	controllers/replica_set_controller.go:134	Validating MongoDB.Spec	{"ReplicaSet": "development/mongodb"}
2021-09-08T21:20:36.786Z	DEBUG	controllers/replica_set_controller.go:143	Ensuring the service exists	{"ReplicaSet": "development/mongodb"}
2021-09-08T21:20:36.815Z	INFO	controllers/replica_set_controller.go:389	The service already exists... moving forward: services "mongodb-svc" already exists	{"ReplicaSet": "development/mongodb"}
2021-09-08T21:20:36.816Z	INFO	controllers/replica_set_controller.go:307	Creating/Updating AutomationConfig	{"ReplicaSet": "development/mongodb"}
2021-09-08T21:20:36.841Z	DEBUG	scram/scram.go:165	Credentials have not changed, using credentials stored in: secret/my-scram-scram-credentials
2021-09-08T21:20:36.841Z	DEBUG	controllers/replica_set_controller.go:428	AutomationConfigMembersThisReconciliation	{"mdb.AutomationConfigMembersThisReconciliation()": 3}
2021-09-08T21:20:36.842Z	DEBUG	controllers/replica_set_controller.go:330	Waiting for agents to reach version 1	{"ReplicaSet": "development/mongodb"}
2021-09-08T21:20:36.842Z	INFO	agent/agent_readiness.go:52	All 3 Agents have reached Goal state	{"ReplicaSet": "development/mongodb"}
2021-09-08T21:20:36.842Z	INFO	controllers/replica_set_controller.go:287	Creating/Updating StatefulSet	{"ReplicaSet": "development/mongodb"}
2021-09-08T21:20:36.846Z	DEBUG	controllers/replica_set_controller.go:297	Ensuring StatefulSet is ready, with type: RollingUpdate	{"ReplicaSet": "development/mongodb"}
2021-09-08T21:20:36.846Z	DEBUG	controllers/replica_set_controller.go:202	Resetting StatefulSet UpdateStrategy to RollingUpdate	{"ReplicaSet": "development/mongodb"}
2021-09-08T21:20:36.849Z	ERROR	controllers/replica_set_controller.go:230	Error updating the status of the MongoDB resource: MongoDBCommunity.mongodbcommunity.mongodb.com "mongodb" is invalid: status.version: Required value{"ReplicaSet": "development/mongodb"}
github.com/mongodb/mongodb-kubernetes-operator/controllers.ReplicaSetReconciler.Reconcile
	/workspace/controllers/replica_set_controller.go:230
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:298
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214
```

It seems that commit 44ed501 applied later on somehow overwrote the fix.
Commenting out [this line](https://github.com/mongodb/mongodb-kubernetes-operator/blob/44ed501acaeb58b523d757025fbf292bec7e024d/config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml#L343) fixes it for now.

**Comment by asychev** [comment]
Same problem for me

**Comment by tibulca** [comment]
Hi @asychev , @trilliot,

we found the regression and fixed it on master [PR 718](https://github.com/mongodb/mongodb-kubernetes-operator/pull/718/files) can you please pull the latest changes and try again?

**Comment by asychev** [comment]
@tibulca maybe you can release 0.7.1 version with this fix only?

**Comment by tibulca** [comment]
@asychev 
the issue was with the CRD, not the operator itself, and was introduced after 0.7.0.
Re-applying the CRD from master should fix the problem in your environment.

**Comment by trilliot** [comment]
Hello @tibulca,
I can confirm the issue is fixed on master.

```
NAME                                      TYPE                                  DATA   AGE
example-mongodb-admin-my-user             Opaque                                4      75s
example-mongodb-agent-password            Opaque                                1      3m46s
example-mongodb-config                    Opaque                                1      3m46s
example-mongodb-keyfile                   Opaque                                1      3m46s
```

Thank you very much :raised_hands:
